services:
  app:
    build:
      context: .docker/php
    image: laravel-app
    container_name: posts_mvp-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - posts_mvp

  web:
    image: nginx:alpine
    container_name: posts_mvp-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - posts_mvp

  db:
    image: postgres:15
    container_name: posts_mvp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: posts_mvp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - posts_mvp

networks:
  posts_mvp:
    driver: bridge

volumes:
  pgdata: